# Generated by Django 6.0.7 on 2026-07-29 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('exchange', models.CharField(blank=True, db_index=True, default='NSE', max_length=10)),
                ('strategy_name', models.CharField(db_index=True, max_length=100)),
                ('overall_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('passed_strategies', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.CharField(choices=[('IGNORE', 'Ignore'), ('WATCHLIST', 'Watchlist'), ('STRONG', 'Strong Candidate'), ('ELITE', 'Elite Setup')], db_index=True, default='IGNORE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=20)),
                ('last_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('entry_low', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('entry_high', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('target_1', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('target_2', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('target_3', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('risk_reward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('telegram_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('alert_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('alert_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-alert_time', '-overall_score'],
                'indexes': [models.Index(fields=['symbol'], name='scanner_sca_symbol_a9623a_idx'), models.Index(fields=['strategy_name'], name='scanner_sca_strateg_96f1cd_idx'), models.Index(fields=['overall_score'], name='scanner_sca_overall_5205fa_idx'), models.Index(fields=['priority'], name='scanner_sca_priorit_9fbc6f_idx'), models.Index(fields=['status'], name='scanner_sca_status_8c640b_idx'), models.Index(fields=['telegram_sent'], name='scanner_sca_telegra_fc7c1f_idx'), models.Index(fields=['email_sent'], name='scanner_sca_email_s_f628e3_idx'), models.Index(fields=['alert_time'], name='scanner_sca_alert_t_d2fb3c_idx')],
            },
        ),
    ]
