# Generated by Django 6.0.7 on 2026-08-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreBreakoutSetupOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('exchange', models.CharField(db_index=True, default='NSE', max_length=10)),
                ('evaluation_session', models.DateField(db_index=True)),
                ('evaluation_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pivot', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('raw_score', models.PositiveSmallIntegerField()),
                ('final_score', models.PositiveSmallIntegerField()),
                ('classification', models.CharField(db_index=True, max_length=20)),
                ('data_quality_state', models.CharField(db_index=True, max_length=10)),
                ('feature_snapshot', models.JSONField(default=dict)),
                ('breakout_occurred', models.BooleanField(blank=True, null=True)),
                ('breakout_session', models.DateField(blank=True, null=True)),
                ('return_1d', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('return_3d', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('return_5d', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('return_10d', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('return_20d', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('maximum_favorable_excursion', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('maximum_adverse_excursion', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('failed_breakout', models.BooleanField(blank=True, null=True)),
                ('evaluated_through_session', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-evaluation_session', 'symbol'],
                'indexes': [models.Index(fields=['evaluation_session', 'classification'], name='scanner_pre_evaluat_23274a_idx'), models.Index(fields=['is_complete', 'evaluation_session'], name='scanner_pre_is_comp_55a20e_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'exchange', 'evaluation_session'), name='uq_prebreakout_setup_session')],
            },
        ),
    ]
