# Generated by Django 6.0.7 on 2026-08-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_prebreakoutsetupoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebreakoutsetupoutcome',
            name='sessions_to_breakout',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
