# Generated by Django 6.0.7 on 2026-07-26 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstox_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='upstoxtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upstoxtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upstoxtoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='upstoxtoken',
            name='token_type',
            field=models.CharField(default='Bearer', max_length=50),
        ),
        migrations.AddField(
            model_name='upstoxtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='upstoxtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upstox_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='upstoxtoken',
            index=models.Index(fields=['is_active'], name='upstox_auth_is_acti_a97e21_idx'),
        ),
        migrations.AddIndex(
            model_name='upstoxtoken',
            index=models.Index(fields=['expires_at'], name='upstox_auth_expires_a7709e_idx'),
        ),
        migrations.AddIndex(
            model_name='upstoxtoken',
            index=models.Index(fields=['created_at'], name='upstox_auth_created_2f4f25_idx'),
        ),
    ]
