# Generated by Django 6.0.7 on 2026-07-25 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=30, unique=True)),
                ('exchange', models.CharField(db_index=True, default='NSE', max_length=20)),
                ('isin', models.CharField(blank=True, db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('series', models.CharField(blank=True, max_length=20)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=150)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_cap', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='companies_c_symbol_15f262_idx'), models.Index(fields=['name'], name='companies_c_name_2d8260_idx'), models.Index(fields=['sector'], name='companies_c_sector_f3add2_idx'), models.Index(fields=['industry'], name='companies_c_industr_6efa2c_idx'), models.Index(fields=['exchange'], name='companies_c_exchang_d7fc97_idx')],
            },
        ),
    ]
