# Generated by Django 6.0.7 on 2026-07-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='upstox_instrument_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['isin'], name='companies_c_isin_352f66_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['upstox_instrument_key'], name='companies_c_upstox__e51488_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='companies_c_is_acti_03043b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['exchange', 'symbol'], name='companies_c_exchang_f6ec11_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['exchange', 'upstox_instrument_key'], name='companies_c_exchang_1f764c_idx'),
        ),
    ]
