# Generated by Django 6.0.7 on 2026-08-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_upstox_instrument_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='instrument_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('invalid', 'Invalid instrument')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='instrument_status_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['instrument_status'], name='companies_c_instrum_895512_idx'),
        ),
    ]
