# Generated by Django 6.0.7 on 2026-08-07 20:39

from django.db import migrations


SUSPENDED_SYMBOLS = ("NARMADA", "TEMBO", "WINSOME", "SABEVENTS")
REASON = "Verified suspended/inactive during Phase 12 reliability audit"


def mark_verified_suspended_instruments(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    Company.objects.filter(symbol__in=SUSPENDED_SYMBOLS, exchange="NSE").update(
        is_active=False,
        instrument_status="suspended",
        instrument_status_reason=REASON,
    )


def restore_previous_active_state(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    Company.objects.filter(
        symbol__in=SUSPENDED_SYMBOLS,
        exchange="NSE",
        instrument_status="suspended",
        instrument_status_reason=REASON,
    ).update(
        is_active=True,
        instrument_status="active",
        instrument_status_reason="",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_company_instrument_status_and_more"),
    ]

    operations = [
        migrations.RunPython(
            mark_verified_suspended_instruments,
            restore_previous_active_state,
        ),
    ]