# Generated by Django 6.0.7 on 2026-09-06 13:01

from django.db import migrations, models


def classify_existing_companies(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    equity_series = {"EQ", "BE", "BZ", "SM", "ST"}
    debt_types = {"SG", "GS", "TB", "GB", "RR"}
    updates = []
    for company in Company.objects.all().iterator(chunk_size=2_000):
        key = str(company.upstox_instrument_key or "").strip()
        segment = key.split("|", 1)[0].upper() if "|" in key else ""
        instrument_type = str(company.series or "").strip().upper()
        isin = str(company.isin or "").strip().upper()
        if segment != "NSE_EQ":
            category = "other"
        elif instrument_type in equity_series and isin.startswith("INE"):
            category = "operating_equity"
        elif instrument_type in equity_series and isin.startswith("INF"):
            category = "etf"
        elif instrument_type in debt_types or instrument_type.startswith("N"):
            category = "debt"
        else:
            category = "other"
        company.provider_segment = segment
        company.provider_instrument_type = instrument_type
        company.security_category = category
        updates.append(company)
    if updates:
        Company.objects.bulk_update(
            updates,
            ["provider_segment", "provider_instrument_type", "security_category"],
            batch_size=2_000,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_mark_verified_suspended_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='history_sync_last_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='history_sync_last_success_session',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='provider_instrument_type',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='provider_security_type',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='provider_segment',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='security_category',
            field=models.CharField(choices=[('operating_equity', 'Operating-company equity'), ('etf', 'Exchange-traded fund'), ('debt', 'Debt or government security'), ('other', 'Other security'), ('unknown', 'Unclassified')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.RunPython(classify_existing_companies, migrations.RunPython.noop),
    ]
