# Generated by Django 6.0.7 on 2026-07-26 07:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOHLC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], default='NSE', max_length=10)),
                ('interval', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minute'), ('15m', '15 Minute'), ('30m', '30 Minute'), ('1h', '1 Hour'), ('1d', 'Daily'), ('1w', 'Weekly'), ('1mo', 'Monthly')], db_index=True, max_length=10)),
                ('open', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('candle_time', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-candle_time'],
                'indexes': [models.Index(fields=['symbol', 'interval'], name='market_mark_symbol_1ae9a8_idx'), models.Index(fields=['symbol', 'candle_time'], name='market_mark_symbol_0a20e8_idx'), models.Index(fields=['interval', 'candle_time'], name='market_mark_interva_42af90_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'exchange', 'interval', 'candle_time'), name='uq_market_candle')],
            },
        ),
        migrations.CreateModel(
            name='MarketQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], db_index=True, default='NSE', max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('last_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('open_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('previous_close', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('change', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('traded_value', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('market_status', models.CharField(choices=[('PREOPEN', 'Pre Open'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('POST', 'Post Market')], db_index=True, default='CLOSED', max_length=20)),
                ('last_trade_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='market_mark_symbol_209a25_idx'), models.Index(fields=['exchange'], name='market_mark_exchang_0cf2ff_idx'), models.Index(fields=['updated_at'], name='market_mark_updated_a83ea9_idx'), models.Index(fields=['market_status'], name='market_mark_market__963048_idx'), models.Index(fields=['symbol', 'exchange'], name='market_mark_symbol_619b00_idx'), models.Index(fields=['exchange', 'updated_at'], name='market_mark_exchang_a1d2a9_idx'), models.Index(fields=['change_percent'], name='market_mark_change__34813a_idx'), models.Index(fields=['volume'], name='market_mark_volume_decaf0_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'exchange'), name='uq_market_symbol_exchange')],
            },
        ),
    ]
