# Generated by Django 6.0.7 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketquote",
            name="provider_timestamp",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
