# Generated by Django 6.0.7 on 2026-08-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketquote_provider_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketohlc',
            name='data_quality_flags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketohlc',
            name='provider_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
