# Generated by Django 6.0.7 on 2026-08-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_mark_verified_suspended_instruments'),
        ('market', '0003_marketohlc_data_quality_flags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudBenchmarkCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(unique=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('provider_timestamp', models.DateTimeField(blank=True, null=True)),
                ('data_quality_flags', models.JSONField(blank=True, default=list)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='CloudQuoteSnapshot',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cloud_quote_snapshot', serialize=False, to='companies.company')),
                ('last_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('previous_close', models.DecimalField(decimal_places=4, max_digits=20)),
                ('change', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('provider_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_trade_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudDailyCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('provider_timestamp', models.DateTimeField(blank=True, null=True)),
                ('data_quality_flags', models.JSONField(blank=True, default=list)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_daily_candles', to='companies.company')),
            ],
            options={
                'ordering': ['-session_date'],
                'constraints': [models.UniqueConstraint(fields=('company', 'session_date'), name='uq_cloud_daily_company_session')],
            },
        ),
    ]
