# Generated by Django 6.0.7 on 2026-09-06 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_history_sync_last_attempt_at_and_more'),
        ('market', '0004_cloud_compact_market_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketquote',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_quotes', to='companies.company'),
        ),
        migrations.AddField(
            model_name='marketquote',
            name='instrument_key',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
