# Generated by Django 6.0.7 on 2026-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_marketquote_company_marketquote_instrument_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudquotesnapshot',
            name='market_status',
            field=models.CharField(choices=[('PREOPEN', 'Pre Open'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('POST', 'Post Market')], db_index=True, default='CLOSED', max_length=20),
        ),
        migrations.AddField(
            model_name='cloudquotesnapshot',
            name='provider_state',
            field=models.CharField(db_index=True, default='DATA_UNAVAILABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='marketquote',
            name='provider_state',
            field=models.CharField(db_index=True, default='DATA_UNAVAILABLE', max_length=30),
        ),
    ]
